# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(389, 453)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.push8 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push8.sizePolicy().hasHeightForWidth())
        self.push8.setSizePolicy(sizePolicy)
        self.push8.setStyleSheet("QPushButton{\n"
"font: 75 20pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(198, 198, 198);\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(85, 255, 0);\n"
"    background-color: rgb(172, 172, 172);\n"
"    border-radius:20px;\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(255, 0, 0);\n"
"        color: rgb(255, 255, 255);\n"
"}")
        self.push8.setObjectName("push8")
        self.gridLayout.addWidget(self.push8, 2, 1, 1, 1)
        self.pushdel = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.pushdel.sizePolicy().hasHeightForWidth())
        self.pushdel.setSizePolicy(sizePolicy)
        self.pushdel.setStyleSheet("QPushButton{\n"
"font: 75 20pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(198, 198, 198);\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(85, 255, 0);\n"
"    background-color: rgb(172, 172, 172);\n"
"    border-radius:20px;\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(255, 0, 0);\n"
"        color: rgb(255, 255, 255);\n"
"}")
        self.pushdel.setObjectName("pushdel")
        self.gridLayout.addWidget(self.pushdel, 1, 3, 1, 1)
        self.push0 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push0.sizePolicy().hasHeightForWidth())
        self.push0.setSizePolicy(sizePolicy)
        self.push0.setStyleSheet("QPushButton{\n"
"font: 75 20pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(198, 198, 198);\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(85, 255, 0);\n"
"    background-color: rgb(172, 172, 172);\n"
"    border-radius:20px;\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(255, 0, 0);\n"
"        color: rgb(255, 255, 255);\n"
"}")
        self.push0.setObjectName("push0")
        self.gridLayout.addWidget(self.push0, 5, 0, 1, 1)
        self.push1 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push1.sizePolicy().hasHeightForWidth())
        self.push1.setSizePolicy(sizePolicy)
        self.push1.setStyleSheet("QPushButton{\n"
"font: 75 20pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(198, 198, 198);\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(85, 255, 0);\n"
"    background-color: rgb(172, 172, 172);\n"
"    border-radius:20px;\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(255, 0, 0);\n"
"        color: rgb(255, 255, 255);\n"
"}")
        self.push1.setObjectName("push1")
        self.gridLayout.addWidget(self.push1, 4, 0, 1, 1)
        self.pushstar = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.pushstar.sizePolicy().hasHeightForWidth())
        self.pushstar.setSizePolicy(sizePolicy)
        self.pushstar.setStyleSheet("QPushButton{\n"
"font: 75 20pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(198, 198, 198);\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(85, 255, 0);\n"
"    background-color: rgb(172, 172, 172);\n"
"    border-radius:20px;\n"
"}\n"
"QPushButton{\n"
"    \n"
"    background-color: rgb(255, 255, 127);\n"
"        color: rgb(255, 255, 255);\n"
"}")
        self.pushstar.setObjectName("pushstar")
        self.gridLayout.addWidget(self.pushstar, 3, 3, 1, 1)
        self.pushclear = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.pushclear.sizePolicy().hasHeightForWidth())
        self.pushclear.setSizePolicy(sizePolicy)
        self.pushclear.setStyleSheet("QPushButton{\n"
"font: 75 20pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(255, 170, 0);\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(85, 255, 0);\n"
"    background-color: rgb(172, 172, 172);\n"
"    border-radius:15px;\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(255, 170, 0);\n"
"        color: rgb(255, 255, 255);\n"
"}")
        self.pushclear.setObjectName("pushclear")
        self.gridLayout.addWidget(self.pushclear, 1, 0, 1, 3)
        self.push6 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push6.sizePolicy().hasHeightForWidth())
        self.push6.setSizePolicy(sizePolicy)
        self.push6.setStyleSheet("QPushButton{\n"
"font: 75 20pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(198, 198, 198);\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(85, 255, 0);\n"
"    background-color: rgb(172, 172, 172);\n"
"    border-radius:20px;\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(255, 0, 0);\n"
"        color: rgb(255, 255, 255);\n"
"}")
        self.push6.setObjectName("push6")
        self.gridLayout.addWidget(self.push6, 3, 2, 1, 1)
        self.push7 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push7.sizePolicy().hasHeightForWidth())
        self.push7.setSizePolicy(sizePolicy)
        self.push7.setStyleSheet("QPushButton{\n"
"font: 75 20pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(198, 198, 198);\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(85, 255, 0);\n"
"    background-color: rgb(172, 172, 172);\n"
"    border-radius:20px;\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(255, 0, 0);\n"
"        color: rgb(255, 255, 255);\n"
"}")
        self.push7.setObjectName("push7")
        self.gridLayout.addWidget(self.push7, 2, 0, 1, 1)
        self.pushpoint = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.pushpoint.sizePolicy().hasHeightForWidth())
        self.pushpoint.setSizePolicy(sizePolicy)
        self.pushpoint.setStyleSheet("QPushButton{\n"
"font: 75 20pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(198, 198, 198);\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(85, 255, 0);\n"
"    background-color: rgb(172, 172, 172);\n"
"    border-radius:20px;\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(255, 0, 0);\n"
"        color: rgb(255, 255, 255);\n"
"}")
        self.pushpoint.setObjectName("pushpoint")
        self.gridLayout.addWidget(self.pushpoint, 5, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(14)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("font: 75 36pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 4)
        self.pushslash = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.pushslash.sizePolicy().hasHeightForWidth())
        self.pushslash.setSizePolicy(sizePolicy)
        self.pushslash.setStyleSheet("QPushButton{\n"
"font: 75 20pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(198, 198, 198);\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(85, 255, 0);\n"
"    background-color: rgb(172, 172, 172);\n"
"    border-radius:20px;\n"
"}\n"
"QPushButton{\n"
"    \n"
"    background-color: rgb(255, 255, 127);\n"
"        color: rgb(255, 255, 255);\n"
"}")
        self.pushslash.setObjectName("pushslash")
        self.gridLayout.addWidget(self.pushslash, 2, 3, 1, 1)
        self.pushplus = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.pushplus.sizePolicy().hasHeightForWidth())
        self.pushplus.setSizePolicy(sizePolicy)
        self.pushplus.setStyleSheet("QPushButton{\n"
"font: 75 20pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(198, 198, 198);\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(85, 255, 0);\n"
"    background-color: rgb(172, 172, 172);\n"
"    border-radius:20px;\n"
"}\n"
"QPushButton{\n"
"    \n"
"    background-color: rgb(255, 255, 127);\n"
"        color: rgb(255, 255, 255);\n"
"}")
        self.pushplus.setObjectName("pushplus")
        self.gridLayout.addWidget(self.pushplus, 5, 3, 1, 1)
        self.push5 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push5.sizePolicy().hasHeightForWidth())
        self.push5.setSizePolicy(sizePolicy)
        self.push5.setStyleSheet("QPushButton{\n"
"font: 75 20pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(198, 198, 198);\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(85, 255, 0);\n"
"    background-color: rgb(172, 172, 172);\n"
"    border-radius:20px;\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(255, 0, 0);\n"
"        color: rgb(255, 255, 255);\n"
"}")
        self.push5.setObjectName("push5")
        self.gridLayout.addWidget(self.push5, 3, 1, 1, 1)
        self.pushminus = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.pushminus.sizePolicy().hasHeightForWidth())
        self.pushminus.setSizePolicy(sizePolicy)
        self.pushminus.setStyleSheet("QPushButton{\n"
"font: 75 20pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(198, 198, 198);\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(85, 255, 0);\n"
"    background-color: rgb(172, 172, 172);\n"
"    border-radius:20px;\n"
"}\n"
"QPushButton{\n"
"    \n"
"    background-color: rgb(255, 255, 127);\n"
"        color: rgb(255, 255, 255);\n"
"}")
        self.pushminus.setObjectName("pushminus")
        self.gridLayout.addWidget(self.pushminus, 4, 3, 1, 1)
        self.push2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push2.sizePolicy().hasHeightForWidth())
        self.push2.setSizePolicy(sizePolicy)
        self.push2.setStyleSheet("QPushButton{\n"
"font: 75 20pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(198, 198, 198);\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(85, 255, 0);\n"
"    background-color: rgb(172, 172, 172);\n"
"    border-radius:20px;\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(255, 0, 0);\n"
"        color: rgb(255, 255, 255);\n"
"}")
        self.push2.setObjectName("push2")
        self.gridLayout.addWidget(self.push2, 4, 1, 1, 1)
        self.pushequal = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.pushequal.sizePolicy().hasHeightForWidth())
        self.pushequal.setSizePolicy(sizePolicy)
        self.pushequal.setStyleSheet("QPushButton{\n"
"font: 75 20pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(198, 198, 198);\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(85, 255, 0);\n"
"    background-color: rgb(172, 172, 172);\n"
"    border-radius:20px;\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(255, 0, 0);\n"
"        color: rgb(255, 255, 255);\n"
"}")
        self.pushequal.setObjectName("pushequal")
        self.gridLayout.addWidget(self.pushequal, 5, 2, 1, 1)
        self.push4 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push4.sizePolicy().hasHeightForWidth())
        self.push4.setSizePolicy(sizePolicy)
        self.push4.setStyleSheet("QPushButton{\n"
"font: 75 20pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(198, 198, 198);\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(85, 255, 0);\n"
"    background-color: rgb(172, 172, 172);\n"
"    border-radius:20px;\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(255, 0, 0);\n"
"        color: rgb(255, 255, 255);\n"
"}")
        self.push4.setObjectName("push4")
        self.gridLayout.addWidget(self.push4, 3, 0, 1, 1)
        self.push9 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push9.sizePolicy().hasHeightForWidth())
        self.push9.setSizePolicy(sizePolicy)
        self.push9.setStyleSheet("QPushButton{\n"
"font: 75 20pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(198, 198, 198);\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(85, 255, 0);\n"
"    background-color: rgb(172, 172, 172);\n"
"    border-radius:20px;\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(255, 0, 0);\n"
"        color: rgb(255, 255, 255);\n"
"}")
        self.push9.setObjectName("push9")
        self.gridLayout.addWidget(self.push9, 2, 2, 1, 1)
        self.push3 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.push3.sizePolicy().hasHeightForWidth())
        self.push3.setSizePolicy(sizePolicy)
        self.push3.setStyleSheet("QPushButton{\n"
"font: 75 20pt \"MS Shell Dlg 2\";\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(198, 198, 198);\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(85, 255, 0);\n"
"    background-color: rgb(172, 172, 172);\n"
"    border-radius:20px;\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(255, 0, 0);\n"
"        color: rgb(255, 255, 255);\n"
"}")
        self.push3.setObjectName("push3")
        self.gridLayout.addWidget(self.push3, 4, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 389, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.push1.clicked.connect(self.method_1)
        self.push2.clicked.connect(self.method_2)
        self.push3.clicked.connect(self.method_3)
        self.push4.clicked.connect(self.method_4)
        self.push5.clicked.connect(self.method_5)
        self.push6.clicked.connect(self.method_6)
        self.push7.clicked.connect(self.method_7)
        self.push8.clicked.connect(self.method_8)
        self.push9.clicked.connect(self.method_9)
        self.push0.clicked.connect(self.method_0)
        self.pushpoint.clicked.connect(self.method_point)
        self.pushplus.clicked.connect(self.method_plus)
        self.pushminus.clicked.connect(self.method_minus)
        self.pushstar.clicked.connect(self.method_star)
        self.pushslash.clicked.connect(self.method_slash)
        self.pushequal.clicked.connect(self.method_equal)
        self.pushclear.clicked.connect(self.method_clear)
        self.pushdel.clicked.connect(self.method_del)

    def method_1(self):
        text=self.label.text()
        self.label.setText(text+"1")
    def method_2(self):
        text=self.label.text()
        self.label.setText(text+"2")
    def method_3(self):
        text=self.label.text()
        self.label.setText(text+"3")
    def method_4(self):
        text=self.label.text()
        self.label.setText(text+"4")
    def method_5(self):
        text=self.label.text()
        self.label.setText(text+"5")
    def method_6(self):
        text=self.label.text()
        self.label.setText(text+"6")
    def method_7(self):
        text=self.label.text()
        self.label.setText(text+"7")
    def method_8(self):
        text=self.label.text()
        self.label.setText(text+"8")
    def method_9(self):
        text=self.label.text()
        self.label.setText(text+"9")
    def method_0(self):
        text=self.label.text()
        self.label.setText(text+"0")
    def method_point(self):
        text=self.label.text()
        self.label.setText(text+".")
    def method_plus(self):
        text=self.label.text()
        self.label.setText(text+"+")
    def method_minus(self):
        text=self.label.text()
        self.label.setText(text+"-")
    def method_star(self):
        text=self.label.text()
        self.label.setText(text+"*")
    def method_slash(self):
        text=self.label.text()
        self.label.setText(text+"/")
    def method_clear(self):
        self.label.setText("")
    def method_del(self):
        text=self.label.text()
        self.label.setText(text[:len(text)-1])
    def method_equal(self):
        text=self.label.text()
        try:
            ans=eval(text)
            self.label.setText(str(ans))
        except:
            self.label.setText("Wrong Input")
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "calculator v1.0"))
        self.push8.setText(_translate("MainWindow", "8"))
        self.pushdel.setText(_translate("MainWindow", "DEL"))
        self.push0.setText(_translate("MainWindow", "0"))
        self.push1.setText(_translate("MainWindow", "1"))
        self.pushstar.setText(_translate("MainWindow", "*"))
        self.pushclear.setText(_translate("MainWindow", "C"))
        self.push6.setText(_translate("MainWindow", "6"))
        self.push7.setText(_translate("MainWindow", "7"))
        self.pushpoint.setText(_translate("MainWindow", "."))
        self.label.setText(_translate("MainWindow", ""))
        self.pushslash.setText(_translate("MainWindow", "/"))
        self.pushplus.setText(_translate("MainWindow", "+"))
        self.push5.setText(_translate("MainWindow", "5"))
        self.pushminus.setText(_translate("MainWindow", "-"))
        self.push2.setText(_translate("MainWindow", "2"))
        self.pushequal.setText(_translate("MainWindow", "="))
        self.push4.setText(_translate("MainWindow", "4"))
        self.push9.setText(_translate("MainWindow", "9"))
        self.push3.setText(_translate("MainWindow", "3"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
